/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
 
/**
 *
 * @author mark
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TaulaBonsais = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaulaTractaments = new javax.swing.JTable();
        NomBonsaiJTF = new javax.swing.JTextField();
        NomBotanicJTF = new javax.swing.JTextField();
        FamiliaJTF = new javax.swing.JTextField();
        EdatJTF = new javax.swing.JTextField();
        DataAltaJTF = new javax.swing.JTextField();
        DataBaixaJTF = new javax.swing.JTextField();
        PropietarisJTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ExitBTN = new javax.swing.JButton();
        InsertBTN = new javax.swing.JButton();
        deleteBonsaiBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("My Bonsai Org");

        TaulaBonsais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TaulaBonsais.setColumnSelectionAllowed(true);
        TaulaBonsais.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(TaulaBonsais);
        TaulaBonsais.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        TaulaTractaments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID BOnsai", "Tipus Tractament", "Data", "Motiu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TaulaTractaments);
        if (TaulaTractaments.getColumnModel().getColumnCount() > 0) {
            TaulaTractaments.getColumnModel().getColumn(0).setResizable(false);
            TaulaTractaments.getColumnModel().getColumn(1).setResizable(false);
            TaulaTractaments.getColumnModel().getColumn(2).setResizable(false);
            TaulaTractaments.getColumnModel().getColumn(3).setResizable(false);
        }

        DataAltaJTF.setText("yyyy-mm-dd");
        DataAltaJTF.setToolTipText("yyyy-mm-dd");
        DataAltaJTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataAltaJTFMouseClicked(evt);
            }
        });

        jLabel1.setText("Nom:");

        jLabel3.setText("Nom Botanic: ");

        jLabel4.setText("Familia: ");

        jLabel5.setText("Edat: ");

        jLabel7.setText("Data Alta: ");

        jLabel6.setText("Data Baixa: ");

        jLabel8.setText("Propietaris:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DataBaixaJTF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PropietarisJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(4, 4, 4)
                                        .addComponent(DataAltaJTF))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(4, 4, 4)
                                        .addComponent(EdatJTF))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FamiliaJTF))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NomBotanicJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NomBonsaiJTF)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomBonsaiJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomBotanicJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FamiliaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EdatJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DataAltaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DataBaixaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PropietarisJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        ExitBTN.setText("Sortir");

        InsertBTN.setText("Insertar");

        deleteBonsaiBTN.setText("Borrar");

        UpdateBTN.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InsertBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBonsaiBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateBTN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {InsertBTN, UpdateBTN, deleteBonsaiBTN});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertBTN)
                    .addComponent(deleteBonsaiBTN)
                    .addComponent(UpdateBTN))
                .addGap(101, 101, 101)
                .addComponent(ExitBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataAltaJTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataAltaJTFMouseClicked
        if(getDataAltaJTF().getText()=="yyy-mm-dd"){
            DataAltaJTF.setText("");
        
        }
    }//GEN-LAST:event_DataAltaJTFMouseClicked

    public JTextField getDataAltaJTF() {
        return DataAltaJTF;
    }

    public void setDataAltaJTF(JTextField DataAltaJTF) {
        this.DataAltaJTF = DataAltaJTF;
    }

    public JTextField getDataBaixaJTF() {
        return DataBaixaJTF;
    }

    public void setDataBaixaJTF(JTextField DataBaixaJTF) {
        this.DataBaixaJTF = DataBaixaJTF;
    }

    public JTextField getEdatJTF() {
        return EdatJTF;
    }

    public void setEdatJTF(JTextField EdatJTF) {
        this.EdatJTF = EdatJTF;
    }

    public JTextField getFamiliaJTF() {
        return FamiliaJTF;
    }

    public void setFamiliaJTF(JTextField FamiliaJTF) {
        this.FamiliaJTF = FamiliaJTF;
    }

    public JButton getInsertBTN() {
        return InsertBTN;
    }

    public void setInsertBTN(JButton InsertBTN) {
        this.InsertBTN = InsertBTN;
    }

    public JTextField getNomBonsaiJTF() {
        return NomBonsaiJTF;
    }

    public void setNomBonsaiJTF(JTextField NomBonsaiJTF) {
        this.NomBonsaiJTF = NomBonsaiJTF;
    }

    public JTextField getNomBotanicJTF() {
        return NomBotanicJTF;
    }

    public void setNomBotanicJTF(JTextField NomBotanicJTF) {
        this.NomBotanicJTF = NomBotanicJTF;
    }

    public JButton getUpdateBTN() {
        return UpdateBTN;
    }

    public void setUpdateBTN(JButton UpdateBTN) {
        this.UpdateBTN = UpdateBTN;
    }

    public JButton getDeleteBonsaiBTN() {
        return deleteBonsaiBTN;
    }

    public void setDeleteBonsaiBTN(JButton deleteBonsaiBTN) {
        this.deleteBonsaiBTN = deleteBonsaiBTN;
    }

    public JButton getExitBTN() {
        return ExitBTN;
    }

    public void setExitBTN(JButton ExitBTN) {
        this.ExitBTN = ExitBTN;
    }

    public JTable getTaulaBonsais() {
        return TaulaBonsais;
    }

    public void setTaulaBonsais(JTable TaulaBonsais) {
        this.TaulaBonsais = TaulaBonsais;
    }

    public JTextField getPropietarisJTF() {
        return PropietarisJTF;
    }

    public void setPropietarisJTF(JTextField PropietarisJTF) {
        this.PropietarisJTF = PropietarisJTF;
    }

   
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DataAltaJTF;
    private javax.swing.JTextField DataBaixaJTF;
    private javax.swing.JTextField EdatJTF;
    private javax.swing.JButton ExitBTN;
    private javax.swing.JTextField FamiliaJTF;
    private javax.swing.JButton InsertBTN;
    private javax.swing.JTextField NomBonsaiJTF;
    private javax.swing.JTextField NomBotanicJTF;
    private javax.swing.JTextField PropietarisJTF;
    private javax.swing.JTable TaulaBonsais;
    private javax.swing.JTable TaulaTractaments;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton deleteBonsaiBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
